name: BasicMusic

configs:
    Debug: debug
    Internal: debug
    AppStore: release

options:
    createIntermediateGroups: true
    minimumXcodeGenVersion: 2.3.0
    deploymentTarget:
    iOS: 14.0
    defaultConfig: Debug
    groupSortPosition: top
    generateEmptyDirectories: true

targets:
  BasicMusic:
    type: application
    platform: iOS
    sources: [BasicMusic]
    deploymentTarget: 14.0
    settings:
      base:
        MARKETING_VERSION: '1.0.0'
        INFOPLIST_FILE: BasicMusic/Resources/Info.plist
        TARGETED_DEVICE_FAMILY: 1
        CURRENT_PROJECT_VERSION: 1
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.busicmusic.debug
          PRODUCT_NAME: BasicMusic
          DISPLAY_NAME: "$(PRODUCT_NAME) $(CONFIGURATION)"
        Internal:
          PRODUCT_BUNDLE_IDENTIFIER: com.busicmusic.internal
          PRODUCT_NAME: BasicMusic
          DISPLAY_NAME: "$(PRODUCT_NAME) $(CONFIGURATION)"
        AppStore:
          PRODUCT_BUNDLE_IDENTIFIER: com.busicmusic.appstore
          PRODUCT_NAME: BasicMusic
          DISPLAY_NAME: "$(PRODUCT_NAME) $(CONFIGURATION)"

schemes:
  Debug:
    templates:
    - ConfigBasedScheme
    run:
      config: Debug
  Internal:
    templates:
    - ConfigBasedScheme
    run:
      config: Internal
  AppStore:
    templates:
    - ConfigBasedScheme
    run:
      config: AppStore
schemeTemplates:
  ConfigBasedScheme:
    build:
      targets:
        BasicMusic: all
    run:
      —Åonfig: "${scheme_name}"
    profile:
      config: "${scheme_name}"
    analyze:
      config: "${scheme_name}"
    archive:
      config: "${scheme_name}"

